"""Route pattern definitions for access policy classification.

Extracted from access_policy.py to keep file sizes manageable.
These tuples of compiled regexes are used by access_policy.py for
route classification and idempotency checks.
"""
from __future__ import annotations

import re

PUBLIC_ROUTES = {
    ("GET", "/healthz"),
    ("GET", "/.well-known/agent-card.json"),
    ("GET", "/.well-known/agent.json"),
    ("GET", "/.well-known/oauth-protected-resource"),
    ("GET", "/.well-known/oauth-authorization-server"),
    ("GET", "/operator"),
    ("GET", "/operator/versioning"),
    ("GET", "/customer"),
    ("GET", "/v1/identity/tokens/jwt/jwks"),
    # OAuth token endpoint uses client_credentials (not API key auth)
    ("POST", "/v1/oauth/token"),
    # SCIM discovery endpoints are public per RFC 7644
    ("GET", "/scim/v2/ServiceProviderConfig"),
    ("GET", "/scim/v2/Schemas"),
    ("GET", "/scim/v2/ResourceTypes"),
}

TENANT_SCOPED_PATTERNS = (
    re.compile(r"^/v1/agents$"),
    re.compile(r"^/v1/agents/[^/]+$"),
    re.compile(r"^/v1/agents/[^/]+/versions$"),
    re.compile(r"^/v1/agents/[^/]+/versions/[^/]+$"),
    re.compile(r"^/v1/agents/[^/]+/versions/[^/]+/behavioral-diff/[^/]+$"),
    re.compile(r"^/v1/agents/[^/]+/compare/[^/]+/[^/]+$"),
    re.compile(r"^/v1/agents/[^/]+/capabilities$"),
    re.compile(r"^/v1/agents/[^/]+/trust$"),
    re.compile(r"^/v1/agents/[^/]+/trust/usage$"),
    re.compile(r"^/v1/agents/[^/]+/trust/v2$"),
    re.compile(r"^/v1/agents/[^/]+/trust/attestation$"),
    re.compile(r"^/v1/namespaces/[^/]+$"),
    re.compile(r"^/v1/discovery/agent-manifest$"),
    re.compile(r"^/v1/delegations/[^/]+/status$"),
    re.compile(r"^/v1/delegations/ceremonies"),
    # Runtime routes require tenant scoping
    re.compile(r"^/v1/runtime/profiles"),
    re.compile(r"^/v1/runtime/sandboxes"),
    re.compile(r"^/v1/runtime/audit"),
)

ADMIN_SCOPED_PATTERNS = (
    re.compile(r"^/v1/compliance/evidence/export$"),
    re.compile(r"^/v1/compliance/evidence$"),
    re.compile(r"^/v1/federation/attestations/export$"),
    re.compile(r"^/v1/system/startup-diagnostics$"),
)

IDENTITY_PATTERNS = (
    re.compile(r"^/v1/identity/agents$"),
    re.compile(r"^/v1/identity/agents/[^/]+$"),
    re.compile(r"^/v1/identity/agents/[^/]+/credentials$"),
    re.compile(r"^/v1/identity/agents/[^/]+/active-sessions$"),
    re.compile(r"^/v1/identity/credentials/[^/]+$"),
    re.compile(r"^/v1/identity/credentials/[^/]+/rotate$"),
    re.compile(r"^/v1/identity/credentials/[^/]+/revoke$"),
    re.compile(r"^/v1/identity/delegation-tokens$"),
    re.compile(r"^/v1/identity/delegation-tokens/verify$"),
    re.compile(r"^/v1/identity/delegation-tokens/[^/]+/chain$"),
    re.compile(r"^/v1/identity/delegation-tokens/[^/]+/revoke$"),
    re.compile(r"^/v1/identity/revocations$"),
    re.compile(r"^/v1/identity/revocations/bulk$"),
    re.compile(r"^/v1/identity/agents/[^/]+/revoke$"),
    re.compile(r"^/v1/identity/trust-registry/domains$"),
    re.compile(r"^/v1/identity/trust-registry/domains/[^/]+$"),
    re.compile(r"^/v1/identity/agents/[^/]+/attest$"),
    re.compile(r"^/v1/identity/attestations/[^/]+/verify$"),
    re.compile(r"^/v1/identity/agents/[^/]+/human-principal$"),
    re.compile(r"^/v1/identity/agents/[^/]+/configuration-checksum$"),
    re.compile(r"^/v1/identity/agents/[^/]+/configuration-checksum/verify$"),
    re.compile(r"^/v1/identity/agents/[^/]+/configuration-checksum/compute$"),
    re.compile(r"^/v1/identity/agents/[^/]+/configuration-checksum/integrity$"),
    re.compile(r"^/v1/identity/agents/[^/]+/blended$"),
    re.compile(r"^/v1/identity/agents/[^/]+/on-behalf-of/verify$"),
    re.compile(r"^/v1/identity/agents/[^/]+/spiffe-id$"),
    re.compile(r"^/v1/identity/agents/[^/]+/svid$"),
    re.compile(r"^/v1/identity/spiffe/verify$"),
    re.compile(r"^/v1/identity/spiffe/bundle$"),
    re.compile(r"^/v1/identity/capability-tokens/issue$"),
    re.compile(r"^/v1/identity/capability-tokens/attenuate$"),
    re.compile(r"^/v1/identity/capability-tokens/verify$"),
    re.compile(r"^/v1/identity/capability-tokens/third-party-block$"),
    re.compile(r"^/v1/identity/lifecycle/provision$"),
    re.compile(r"^/v1/identity/lifecycle/agents/[^/]+/rotate$"),
    re.compile(r"^/v1/identity/lifecycle/alerts/expiry$"),
    re.compile(r"^/v1/identity/lifecycle/alerts/rotation$"),
    re.compile(r"^/v1/identity/lifecycle/agents/[^/]+/status$"),
    re.compile(r"^/v1/identity/lifecycle/agents/[^/]+/deprovision$"),
    re.compile(r"^/v1/identity/analytics/credentials$"),
    re.compile(r"^/v1/identity/analytics/identities$"),
    re.compile(r"^/v1/identity/analytics/delegations$"),
    re.compile(r"^/v1/identity/analytics/health$"),
    # DID/VC endpoints
    re.compile(r"^/v1/identity/dids$"),
    re.compile(r"^/v1/identity/dids/[^/]+/resolve$"),
    re.compile(r"^/v1/identity/dids/[^/]+/deactivate$"),
    re.compile(r"^/v1/identity/vcs$"),
    re.compile(r"^/v1/identity/vcs/issue$"),
    re.compile(r"^/v1/identity/vcs/[^/]+/verify$"),
    re.compile(r"^/v1/identity/vcs/[^/]+/revoke$"),
    re.compile(r"^/v1/identity/tokens/jwt$"),
    re.compile(r"^/v1/identity/tokens/jwt/verify$"),
    re.compile(r"^/v1/identity/tokens/jwt/jwks$"),
    # OAuth endpoints
    re.compile(r"^/v1/oauth/register$"),
    re.compile(r"^/v1/oauth/token$"),
    # PQC endpoints
    re.compile(r"^/v1/identity/pqc/keypairs$"),
    re.compile(r"^/v1/identity/pqc/keypairs/[^/]+$"),
    re.compile(r"^/v1/identity/pqc/sign$"),
    re.compile(r"^/v1/identity/pqc/verify$"),
    # Agent discovery & inventory endpoints
    re.compile(r"^/v1/discovery/inventory$"),
    re.compile(r"^/v1/discovery/inventory/[^/]+$"),
    re.compile(r"^/v1/discovery/shadow-agents$"),
    re.compile(r"^/v1/discovery/posture$"),
    # Approval workflow endpoints
    re.compile(r"^/v1/approval/requests$"),
    re.compile(r"^/v1/approval/requests/[^/]+$"),
    re.compile(r"^/v1/approval/requests/[^/]+/decide$"),
    re.compile(r"^/v1/approval/check$"),
    re.compile(r"^/v1/approval/pending$"),
    re.compile(r"^/v1/approval/policies$"),
    # Intent-aware access logging endpoints
    re.compile(r"^/v1/intent/log$"),
    re.compile(r"^/v1/intent/summary/[^/]+$"),
    re.compile(r"^/v1/intent/evaluate$"),
    re.compile(r"^/v1/intent/policies$"),
    # Session-based ephemeral grant endpoints
    re.compile(r"^/v1/grants$"),
    re.compile(r"^/v1/grants/[^/]+$"),
    re.compile(r"^/v1/grants/[^/]+/consume$"),
    re.compile(r"^/v1/grants/[^/]+/revoke$"),
    re.compile(r"^/v1/grants/check$"),
    re.compile(r"^/v1/grants/usage$"),
    # Audit event streaming and webhook endpoints
    re.compile(r"^/v1/audit/events$"),
    re.compile(r"^/v1/audit/stats$"),
    re.compile(r"^/v1/audit/webhooks$"),
    re.compile(r"^/v1/audit/webhooks/[^/]+$"),
    re.compile(r"^/v1/audit/webhooks/[^/]+/deactivate$"),
    re.compile(r"^/v1/audit/webhooks/[^/]+/activate$"),
    re.compile(r"^/v1/audit/webhooks/[^/]+/test$"),
    re.compile(r"^/v1/audit/deliveries$"),
    re.compile(r"^/v1/audit/dead-letters$"),
    re.compile(r"^/v1/audit/dead-letters/retry$"),
    re.compile(r"^/v1/audit/simulate-failure$"),
    # Access review / certification campaign endpoints
    re.compile(r"^/v1/access-review/campaigns$"),
    re.compile(r"^/v1/access-review/campaigns/[^/]+$"),
    re.compile(r"^/v1/access-review/campaigns/[^/]+/progress$"),
    re.compile(r"^/v1/access-review/campaigns/[^/]+/items$"),
    re.compile(r"^/v1/access-review/items/[^/]+/decide$"),
    re.compile(r"^/v1/access-review/compliance$"),
    # Policy-as-Code rule engine endpoints
    re.compile(r"^/v1/policy/rules$"),
    re.compile(r"^/v1/policy/rules/[^/]+$"),
    re.compile(r"^/v1/policy/rules/[^/]+/versions$"),
    re.compile(r"^/v1/policy/evaluate$"),
    re.compile(r"^/v1/policy/evaluations$"),
    # Agent session management endpoints
    re.compile(r"^/v1/sessions$"),
    re.compile(r"^/v1/sessions/stats$"),
    re.compile(r"^/v1/sessions/[^/]+$"),
    re.compile(r"^/v1/sessions/[^/]+/touch$"),
    re.compile(r"^/v1/sessions/[^/]+/terminate$"),
    re.compile(r"^/v1/sessions/force-logout$"),
    re.compile(r"^/v1/sessions/policies$"),
    re.compile(r"^/v1/sessions/policies/[^/]+$"),
    # Secret rotation vault endpoints
    re.compile(r"^/v1/vault/secrets$"),
    re.compile(r"^/v1/vault/secrets/expiring$"),
    re.compile(r"^/v1/vault/secrets/rotation-due$"),
    re.compile(r"^/v1/vault/secrets/[^/]+$"),
    re.compile(r"^/v1/vault/secrets/[^/]+/access$"),
    re.compile(r"^/v1/vault/secrets/[^/]+/rotate$"),
    re.compile(r"^/v1/vault/secrets/[^/]+/revoke$"),
    re.compile(r"^/v1/vault/rotation-history$"),
    # Entitlement catalog endpoints
    re.compile(r"^/v1/entitlements$"),
    re.compile(r"^/v1/entitlements/stats$"),
    re.compile(r"^/v1/entitlements/[^/]+$"),
    re.compile(r"^/v1/entitlements/assignments$"),
    re.compile(r"^/v1/entitlements/assignments/[^/]+/revoke$"),
    re.compile(r"^/v1/entitlements/agents/[^/]+$"),
    re.compile(r"^/v1/entitlements/roles$"),
    re.compile(r"^/v1/entitlements/roles/[^/]+$"),
    re.compile(r"^/v1/entitlements/roles/[^/]+/members$"),
    re.compile(r"^/v1/entitlements/roles/[^/]+/members/remove$"),
    # RBAC endpoints
    re.compile(r"^/v1/rbac/roles$"),
    re.compile(r"^/v1/rbac/roles/[^/]+$"),
    re.compile(r"^/v1/rbac/stats$"),
    re.compile(r"^/v1/rbac/assignments$"),
    re.compile(r"^/v1/rbac/assignments/remove$"),
    re.compile(r"^/v1/rbac/check$"),
    re.compile(r"^/v1/rbac/agents/[^/]+/roles$"),
    re.compile(r"^/v1/rbac/check-log$"),
    re.compile(r"^/v1/rbac/sod-constraints$"),
    # Key management endpoints
    re.compile(r"^/v1/keys$"),
    re.compile(r"^/v1/keys/stats$"),
    re.compile(r"^/v1/keys/usage$"),
    re.compile(r"^/v1/keys/record-usage$"),
    re.compile(r"^/v1/keys/[^/]+$"),
    re.compile(r"^/v1/keys/[^/]+/rotate$"),
    re.compile(r"^/v1/keys/[^/]+/revoke$"),
    # Consent registry endpoints
    re.compile(r"^/v1/consents$"),
    re.compile(r"^/v1/consents/stats$"),
    re.compile(r"^/v1/consents/check$"),
    re.compile(r"^/v1/consents/audit-trail$"),
    re.compile(r"^/v1/consents/[^/]+$"),
    re.compile(r"^/v1/consents/[^/]+/revoke$"),
    # Agent group endpoints
    re.compile(r"^/v1/groups$"),
    re.compile(r"^/v1/groups/stats$"),
    re.compile(r"^/v1/groups/agents/[^/]+$"),
    re.compile(r"^/v1/groups/agents/[^/]+/effective-policy$"),
    re.compile(r"^/v1/groups/[^/]+$"),
    re.compile(r"^/v1/groups/[^/]+/policies$"),
    re.compile(r"^/v1/groups/[^/]+/members$"),
    re.compile(r"^/v1/groups/[^/]+/members/remove$"),
    # Rate limit policy endpoints
    re.compile(r"^/v1/rate-policies$"),
    re.compile(r"^/v1/rate-policies/stats$"),
    re.compile(r"^/v1/rate-policies/check$"),
    re.compile(r"^/v1/rate-policies/violations$"),
    re.compile(r"^/v1/rate-policies/[^/]+$"),
    # Credential binding endpoints
    re.compile(r"^/v1/credential-bindings$"),
    re.compile(r"^/v1/credential-bindings/stats$"),
    re.compile(r"^/v1/credential-bindings/validate$"),
    re.compile(r"^/v1/credential-bindings/validations$"),
    re.compile(r"^/v1/credential-bindings/[^/]+$"),
    re.compile(r"^/v1/credential-bindings/[^/]+/deactivate$"),
    # Activity monitoring endpoints
    re.compile(r"^/v1/activity$"),
    re.compile(r"^/v1/activity/stats$"),
    re.compile(r"^/v1/activity/summary/[^/]+$"),
    re.compile(r"^/v1/activity/alerts$"),
    re.compile(r"^/v1/activity/alerts/[^/]+$"),
    re.compile(r"^/v1/activity/alerts/[^/]+/acknowledge$"),
    re.compile(r"^/v1/activity/[^/]+$"),
    # Environment access control endpoints
    re.compile(r"^/v1/environments$"),
    re.compile(r"^/v1/environments/stats$"),
    re.compile(r"^/v1/environments/promotions$"),
    re.compile(r"^/v1/environments/policies$"),
    re.compile(r"^/v1/environments/check$"),
    re.compile(r"^/v1/environments/promote$"),
    re.compile(r"^/v1/environments/[^/]+$"),
    re.compile(r"^/v1/environments/[^/]+/register$"),
    re.compile(r"^/v1/environments/[^/]+/unregister$"),
    # Scope narrowing endpoints
    re.compile(r"^/v1/scope-narrowing$"),
    re.compile(r"^/v1/scope-narrowing/stats$"),
    re.compile(r"^/v1/scope-narrowing/log$"),
    re.compile(r"^/v1/scope-narrowing/validate$"),
    re.compile(r"^/v1/scope-narrowing/[^/]+$"),
    re.compile(r"^/v1/scope-narrowing/[^/]+/revoke$"),
    # IP allowlist endpoints
    re.compile(r"^/v1/ip-rules$"),
    re.compile(r"^/v1/ip-rules/stats$"),
    re.compile(r"^/v1/ip-rules/access-log$"),
    re.compile(r"^/v1/ip-rules/check$"),
    re.compile(r"^/v1/ip-rules/[^/]+$"),
    re.compile(r"^/v1/ip-rules/[^/]+/disable$"),
    # Capability quota endpoints
    re.compile(r"^/v1/quotas$"),
    re.compile(r"^/v1/quotas/stats$"),
    re.compile(r"^/v1/quotas/violations$"),
    re.compile(r"^/v1/quotas/check$"),
    re.compile(r"^/v1/quotas/usage/[^/]+$"),
    re.compile(r"^/v1/quotas/[^/]+$"),
)

# Endpoints with local write semantics where idempotency is intentionally optional.
IDEMPOTENCY_OPTIONAL_PATTERNS = (
    re.compile(r"^/v1/auth/tokens$"),
    re.compile(r"^/v1/provenance/manifests/sign$"),
    re.compile(r"^/v1/provenance/manifests/verify$"),
    re.compile(r"^/v1/provenance/artifacts/sign$"),
    re.compile(r"^/v1/provenance/artifacts/verify$"),
    re.compile(r"^/v1/capabilities/search$"),
    re.compile(r"^/v1/capabilities/match$"),
    re.compile(r"^/v1/capabilities/recommend$"),
    re.compile(r"^/v1/discovery/search$"),
    re.compile(r"^/v1/discovery/contract-match$"),
    re.compile(r"^/v1/discovery/compatibility$"),
    re.compile(r"^/v1/operator/refresh$"),
    re.compile(r"^/v1/billing/invoices/[^/]+/reconcile$"),
    re.compile(r"^/v1/delegations$"),
    re.compile(r"^/v1/identity/agents$"),
    re.compile(r"^/v1/identity/agents/[^/]+/credentials$"),
    re.compile(r"^/v1/identity/credentials/[^/]+/rotate$"),
    re.compile(r"^/v1/identity/credentials/[^/]+/revoke$"),
    re.compile(r"^/v1/identity/delegation-tokens$"),
    re.compile(r"^/v1/identity/delegation-tokens/verify$"),
    re.compile(r"^/v1/identity/delegation-tokens/[^/]+/revoke$"),
    re.compile(r"^/v1/identity/revocations/bulk$"),
    re.compile(r"^/v1/identity/agents/[^/]+/revoke$"),
    re.compile(r"^/v1/identity/trust-registry/domains$"),
    re.compile(r"^/v1/identity/agents/[^/]+/attest$"),
    re.compile(r"^/v1/identity/agents/[^/]+/human-principal$"),
    re.compile(r"^/v1/identity/agents/[^/]+/configuration-checksum$"),
    re.compile(r"^/v1/identity/agents/[^/]+/configuration-checksum/compute$"),
    re.compile(r"^/v1/identity/agents/[^/]+/configuration-checksum/integrity$"),
    re.compile(r"^/v1/identity/agents/[^/]+/on-behalf-of/verify$"),
    re.compile(r"^/v1/identity/agents/[^/]+/svid$"),
    re.compile(r"^/v1/identity/spiffe/verify$"),
    re.compile(r"^/v1/identity/spiffe/bundle$"),
    re.compile(r"^/v1/identity/capability-tokens/issue$"),
    re.compile(r"^/v1/identity/capability-tokens/attenuate$"),
    re.compile(r"^/v1/identity/capability-tokens/verify$"),
    re.compile(r"^/v1/identity/capability-tokens/third-party-block$"),
    re.compile(r"^/v1/identity/lifecycle/provision$"),
    re.compile(r"^/v1/identity/lifecycle/agents/[^/]+/rotate$"),
    re.compile(r"^/v1/identity/lifecycle/agents/[^/]+/deprovision$"),
    re.compile(r"^/v1/identity/dids$"),
    re.compile(r"^/v1/identity/dids/[^/]+/deactivate$"),
    re.compile(r"^/v1/identity/vcs/issue$"),
    re.compile(r"^/v1/identity/vcs/[^/]+/revoke$"),
    re.compile(r"^/v1/compliance/soc2/evidence$"),
    re.compile(r"^/v1/compliance/soc2/evidence-package$"),
    re.compile(r"^/v1/policy/decisions$"),
    re.compile(r"^/v1/identity/tokens/jwt$"),
    re.compile(r"^/v1/identity/tokens/jwt/verify$"),
    re.compile(r"^/v1/oauth/register$"),
    re.compile(r"^/v1/oauth/token$"),
    re.compile(r"^/v1/federation/execute$"),
    re.compile(r"^/v1/runtime/profiles$"),
    re.compile(r"^/v1/runtime/profiles/[^/]+$"),
    re.compile(r"^/v1/runtime/sandboxes$"),
    re.compile(r"^/v1/runtime/sandboxes/[^/]+$"),
    re.compile(r"^/v1/runtime/sandboxes/[^/]+/execute$"),
    re.compile(r"^/v1/runtime/sandboxes/[^/]+/complete$"),
    re.compile(r"^/v1/runtime/sandboxes/[^/]+/terminate$"),
    re.compile(r"^/v1/runtime/sandboxes/delegated$"),
    re.compile(r"^/v1/runtime/sandboxes/leased$"),
    re.compile(r"^/v1/runtime/audit/evidence$"),
    re.compile(r"^/v1/eval/adversarial/run$"),
    re.compile(r"^/v1/eval/adversarial/prompt-injection$"),
    re.compile(r"^/v1/eval/adversarial/scope-escalation$"),
    re.compile(r"^/v1/agents/[^/]+/trust/attestation$"),
    re.compile(r"^/v1/runtime/integrity/baselines$"),
    re.compile(r"^/v1/runtime/integrity/check$"),
    re.compile(r"^/v1/policy/fides/labels$"),
    re.compile(r"^/v1/policy/fides/clearances$"),
    re.compile(r"^/v1/policy/fides/check-read$"),
    re.compile(r"^/v1/policy/fides/check-write$"),
    re.compile(r"^/v1/policy/fides/taint$"),
    re.compile(r"^/v1/delegations/ceremonies$"),
    re.compile(r"^/v1/delegations/ceremonies/[^/]+/vote$"),
    re.compile(r"^/v1/threat-intel/indicators$"),
    re.compile(r"^/v1/threat-intel/check$"),
    re.compile(r"^/v1/threat-intel/feeds$"),
    re.compile(r"^/v1/federation/mesh/nodes$"),
    re.compile(r"^/v1/federation/mesh/nodes/[^/]+/heartbeat$"),
    re.compile(r"^/v1/federation/mesh/nodes/[^/]+/deregister$"),
    re.compile(r"^/v1/federation/mesh/policies$"),
    re.compile(r"^/v1/federation/mesh/check$"),
    re.compile(r"^/v1/runtime/k8s/pod-spec$"),
    re.compile(r"^/v1/runtime/k8s/network-policy$"),
    re.compile(r"^/v1/identity/pqc/keypairs$"),
    re.compile(r"^/v1/identity/pqc/sign$"),
    re.compile(r"^/v1/identity/pqc/verify$"),
    re.compile(r"^/v1/discovery/inventory$"),
    re.compile(r"^/v1/discovery/inventory/[^/]+$"),
    re.compile(r"^/v1/discovery/shadow-agents$"),
    re.compile(r"^/v1/discovery/posture$"),
    re.compile(r"^/v1/approval/requests$"),
    re.compile(r"^/v1/approval/requests/[^/]+/decide$"),
    re.compile(r"^/v1/approval/check$"),
    re.compile(r"^/v1/approval/policies$"),
    re.compile(r"^/v1/intent/log$"),
    re.compile(r"^/v1/intent/evaluate$"),
    re.compile(r"^/v1/intent/policies$"),
    re.compile(r"^/v1/grants$"),
    re.compile(r"^/v1/grants/[^/]+/consume$"),
    re.compile(r"^/v1/grants/[^/]+/revoke$"),
    re.compile(r"^/v1/grants/check$"),
    re.compile(r"^/v1/audit/events$"),
    re.compile(r"^/v1/audit/webhooks$"),
    re.compile(r"^/v1/audit/webhooks/[^/]+/deactivate$"),
    re.compile(r"^/v1/audit/webhooks/[^/]+/activate$"),
    re.compile(r"^/v1/audit/webhooks/[^/]+/test$"),
    re.compile(r"^/v1/audit/dead-letters/retry$"),
    re.compile(r"^/v1/audit/simulate-failure$"),
    re.compile(r"^/v1/access-review/campaigns$"),
    re.compile(r"^/v1/access-review/campaigns/[^/]+/items$"),
    re.compile(r"^/v1/access-review/items/[^/]+/decide$"),
    re.compile(r"^/v1/policy/rules$"),
    re.compile(r"^/v1/policy/rules/[^/]+$"),
    re.compile(r"^/v1/policy/evaluate$"),
    re.compile(r"^/v1/sessions$"),
    re.compile(r"^/v1/sessions/[^/]+/touch$"),
    re.compile(r"^/v1/sessions/[^/]+/terminate$"),
    re.compile(r"^/v1/sessions/force-logout$"),
    re.compile(r"^/v1/sessions/policies$"),
    re.compile(r"^/v1/vault/secrets$"),
    re.compile(r"^/v1/vault/secrets/[^/]+/access$"),
    re.compile(r"^/v1/vault/secrets/[^/]+/rotate$"),
    re.compile(r"^/v1/vault/secrets/[^/]+/revoke$"),
    re.compile(r"^/v1/entitlements$"),
    re.compile(r"^/v1/entitlements/assignments$"),
    re.compile(r"^/v1/entitlements/assignments/[^/]+/revoke$"),
    re.compile(r"^/v1/entitlements/roles$"),
    re.compile(r"^/v1/entitlements/roles/[^/]+/members$"),
    re.compile(r"^/v1/entitlements/roles/[^/]+/members/remove$"),
    re.compile(r"^/v1/rbac/roles$"),
    re.compile(r"^/v1/rbac/assignments$"),
    re.compile(r"^/v1/rbac/assignments/remove$"),
    re.compile(r"^/v1/rbac/check$"),
    re.compile(r"^/v1/rbac/sod-constraints$"),
    re.compile(r"^/v1/keys$"),
    re.compile(r"^/v1/keys/record-usage$"),
    re.compile(r"^/v1/keys/[^/]+/rotate$"),
    re.compile(r"^/v1/keys/[^/]+/revoke$"),
    re.compile(r"^/v1/consents$"),
    re.compile(r"^/v1/consents/check$"),
    re.compile(r"^/v1/consents/[^/]+/revoke$"),
    re.compile(r"^/v1/groups$"),
    re.compile(r"^/v1/groups/[^/]+/policies$"),
    re.compile(r"^/v1/groups/[^/]+/members$"),
    re.compile(r"^/v1/groups/[^/]+/members/remove$"),
    re.compile(r"^/v1/rate-policies$"),
    re.compile(r"^/v1/rate-policies/check$"),
    re.compile(r"^/v1/rate-policies/[^/]+$"),
    re.compile(r"^/v1/credential-bindings$"),
    re.compile(r"^/v1/credential-bindings/validate$"),
    re.compile(r"^/v1/credential-bindings/[^/]+/deactivate$"),
    re.compile(r"^/v1/activity$"),
    re.compile(r"^/v1/activity/alerts$"),
    re.compile(r"^/v1/activity/alerts/[^/]+/acknowledge$"),
    re.compile(r"^/v1/environments$"),
    re.compile(r"^/v1/environments/policies$"),
    re.compile(r"^/v1/environments/check$"),
    re.compile(r"^/v1/environments/promote$"),
    re.compile(r"^/v1/environments/[^/]+/register$"),
    re.compile(r"^/v1/environments/[^/]+/unregister$"),
    re.compile(r"^/v1/scope-narrowing$"),
    re.compile(r"^/v1/scope-narrowing/validate$"),
    re.compile(r"^/v1/scope-narrowing/[^/]+/revoke$"),
    re.compile(r"^/v1/ip-rules$"),
    re.compile(r"^/v1/ip-rules/check$"),
    re.compile(r"^/v1/ip-rules/[^/]+/disable$"),
    re.compile(r"^/v1/quotas$"),
    re.compile(r"^/v1/quotas/check$"),
    re.compile(r"^/v1/quotas/[^/]+$"),
)
